### ISSUE TITLE
change output of MissingFilesError?

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#131]
```
{
    "error": {
        "type": "MissingFilesError",
        "value": "You seem to be missing these required files:\ncaesar.c\nYou are currently in: /home/chad/Documents/cs50/check50, did you perhaps intend another directory?"
    },
    "version": "3.0.0"
}
```

So now that I need to check for `MissingFilesError`, I'm not sure we need to hardcode the error's message. Could we instead add a `cwd` key and a `files` key, the latter of whose values is an `Array` of the missing filepaths? Then the client can render the message however it wants? E.g., in lab.cs50.io, I'd render `files` as a `ul`, and perhaps in submit.cs50.io too.

**Comment by crossroads1112** [comment]
Hmmm... `MissingFileError`s aren't the only kind of errors so for extensibility purposes we probably need a more robust interface here. We could do the same thing we do with `Failure` in which we have each of our exceptions define a `payload` attribute if they need to communicate extra info:

```python
# lib50.Error
class Error(Exception):
    def __init__(self, message):
        self.message = message
        self.payload = {}

    def __str__(self):
        return self.message

class MissingFileError(Error):
    def __init__(self, files):
        super().__init__("You seem to be...")
        self.payload.update({"files": files, "dir": os.getcwd()})
```
which would result in JSON like:

```json
{
    "error": {
        "type": "MissingFileError",
        "message": "You seem to be...",
        "data": {
            "dir": "/root/sandbox",
            "files": ["caesar.c"],
        },
     "version": "3.0.0"
}
```
JSON from some other exception that we didn't define would like:

```json
{
    "error": {
        "type": "ValueError",
        "message": "too many values to unpack",
        "data": {}
    },
     "version": "3.0.0"
}
```

Note that in the `cause` field we intentionally didn't include the type since check writers could arbitrarily subclass our own exceptions. This is not so much a concern here since these are all exceptions we define ourselves.

**Comment by dmalan** [comment]
`data` looks handy if we can indeed add that.

For `cause`, to be honest, that gets interesting... If subclasses all extend `CheckError` (or what not), could we not just include full-qualified `type` values, a la `CheckError.CustomClass`? And a client can just split on `.` if it wants to detect a prefix match for an otherwise unfamiliar error?

**Comment by crossroads1112** [comment]
The syntax is a bit odd, since `.`s generally don't denote inheritance in Python (might as well return a list of classes in that case). More importantly though, thanks to multiple inheritance, it isn't necessarily a linear ancestry, but rather a tree as any class can potentially have more than one parent. We could, pass this tree along in the JSON but it just seems... messy. Hence this is why we settled on duck typing in this case.

**Comment by Jelleas** [comment]
There's now always a `data` field within `error` that carries any additional information that the exception carried. Currently only `MissingFilesError` carries additional info in the form of `files` and `dir`. With this change the output will now be:

```
{
    "error": {
        "type": "MissingFileError",
        "message": "You seem to be...",
        "data": {
            "dir": "/root/sandbox",
            "files": ["caesar.c"],
        },
     "version": "3.0.0"
}
```
