### ISSUE TITLE
add support for only running a specific check (and its dependencies)

### ISSUE THREAD

**Issue by dmalan** [cs50/check50#155]
E.g., to speed up CS50 Lab's button.

**Comment by Jelleas** [comment]
implemented in https://github.com/cs50/check50/tree/devdev. Running check50 with:

```
check50 <slug> --target <check_name> <check_name> ...
```

Allows you to run only the checks you target (by name), and necessarily their dependencies. For instance, this runs just the checks `withspaces` and `noarg` from https://github.com/cs50/problems/blob/2018/x/vigenere/__init__.py:

```
check50 cs50/problems/2018/x/vigenere --target withspaces noarg
```

As a result you will only see the results of those checks, even though their dependencies (`exists` and `compiles` here) are also run.

In case a dependency fails, for instance the check `compiles` fails, and this causes a targeted check to fail, check50 will also show `compiles` in its output. Reason being, the user would otherwise just see a frowny face without explanation on what went wrong.

**Comment by dmalan** [comment]
Nice. Can we include the dependencies in the JSON output (for labs)?

**Comment by Jelleas** [comment]
To clarify, even in the instance a targeted check passes, we would include and show all the dependencies?

**Comment by dmalan** [comment]
Indeed, I think that'd be helpful. But aok to omit checks that aren't along the dependency chain (or just include their keys with `null` values).

**Comment by Jelleas** [comment]
Targeted checks now show all dependencies in the output. If `noarg` depends on `exists` and `compiles`, you will always see those three checks if you target `noarg`.

Other checks are omitted if they are not part of the dependency chain.

Implemented in https://github.com/cs50/check50/commit/bef37fe333223215a738dd457411c9109383b8d5
