### ISSUE TITLE
.stdout() partial output

### ISSUE THREAD

**Issue by bjorn-out** [cs50/check50#194]
It should be possible to get output (without specifying a string to look for) for `n` seconds, without causing an exception if the program is still running after those `n` seconds.

**Example**
Students implement an old text-based game called Crowther's Adventure based on provided datafiles. This program has a loop which constantly requires the user to provide a new command. After running a command, the game doesn't quit, ofcourse. We want to run some custom logic on the output of a command, for which the default options for `stdout()` aren't suitable. However, running `test = check.stdin('COMMAND').stdout(timeout=5)` raises a timeout exception, as the program hasn't quit after 5 seconds. I would expect this to just return any output gathered within 5 seconds of running it.

I have attempted to implement this myself and create a pull request for check50, but I can't quite seem to figure it out. Maybe someone could point me in the right direction? I'd be happy to implement this myself :)

Thanks!

**Comment by crossroads1112** [comment]
Ideally, if your problem supports this, you would pass whatever input is necessary to "quit" the game, and then call `.stdout()` to get the full output of the program and do your parsing from there. Trying to absorb all output within e.g. 5 seconds while the program is still running opens you up to all kinds of buffering/OS-related issues that could give you all kinds of headaches. 

For example, it's possible that the student's program did print something out, but it's still sitting in the OS's stdout buffer, and since the program isn't exiting or flushing the buffer manually, it never actually makes it to check50 so they fail the check. Believe me, writing check50 meant dealing with all kinds of stuff like this, and it's not fun. Passing in the input necessary to "quit" the game and then calling "stdout" saves you here.

However, if you really, really need to do this, then you can do something like this (though again, I really don't recommend it for the reasons above):

```
try:
    child = check50.run("./student_program").stdout(timeout=5)
except check50.Failure:
    output = child.process.before

```

This isn't part of the official API, and frankly I'm okay with that since doing this opens you up to all kinds of undefined behavior, but that will *probably* work.
