### ISSUE TITLE
log levels, --log, --log-level, --verbose

### ISSUE THREAD

**Issue by kzidane** [cs50/check50#207]
I was gonna reply to @crossroads1112's comment https://github.com/cs50/check50/pull/206#issuecomment-625980981 but I thought maybe opening a new issue would be better since this PR is merged.

I actually thought we left `choices` as it was after all @Jelleas (i.e., `["debug", "info"]`) but maybe I was looking at a cached version. It seems there's no clean way to list the log level names unfortunately so maybe we should just hard-code their names. It's not like they change everyday anyway.  And good point, @crossroads1112 regarding `NOSET`. I guess that would be equivalent to a `--quiet` option that I don't think we have so perhaps we should add that. While we're at it, is there a reason why `--log` exists at all? I get that it lets you see the logs from the checks, but why is that not simply one of the log levels (e.g., `debug`) for example? Or perhaps `info` since it's lower than `debug` and then `debug` would show more `check50` logs.

And should we change `--verbose` to `--log-level` (and remove `--log` in case it just becomes another log level) to be consistent with other tools?

**Comment by Jelleas** [comment]
The only thing `--log` does is show the log from each check in the ANSI output:

![image](https://user-images.githubusercontent.com/1257775/81542911-ab24e500-9375-11ea-9cf9-c729e27964ee.png)

I believe `--log` existed before the web UI, and was previously the only way to get access to these logs. However, now that the web UI and JSON output exist, and that we always show the log output in these (except in the case of `hidden` checks, but don't worry about that), you could argue that `--log` is a little redundant. Come to think of it, I don't think I've ever actually seen anyone use `--log`. On that note, I'm okay with cutting it altogether. @crossroads1112 thoughts?

`--verbose` to `--log-level`. Yes, if we drop `--log`.

"just hard-code their names" I hate everything. But you're probably right.

**Comment by crossroads1112** [comment]
Can we get rid of NOTSET? It's literally the same as not passing the option at all, right?

**Comment by crossroads1112** [comment]
Also, we need to change the error message in `check50.c._check_valgrind` because it says to rerun with `--log` to see the full valgrind output.

**Comment by crossroads1112** [comment]
As for --log vs the others, I'm kinda torn. 

First, `--verbose` has more or less the same effect across every one of our tools, namely that it displays the full error message if an exception is thrown rather than the "Contact sysadmins" one. Now this is no longer the case per the latest change `--verbose` takes an argument so `check50` is now different from the other tools.

Second, I think the check log is conceptually at a different level than the lib50 logs. The check log isn't really intended to be hidden, it's in the html ui for example, whereas the lib50 logs aren't directly relevant to students.

My opinion is that we remove `--log` and fold it into `--log-level x` (not sure what x is yet) and we keep verbose as an alias for that log-level to maintain consistency with our other tools.

**Comment by Jelleas** [comment]
In my latest PR @ https://github.com/cs50/check50/pull/208, I removed `--log` and changed `--verbose` back to what it was. It now, like every other tool, shows the stacktrace instead of email Kareem.

`--log-level x` became one of five options as per https://docs.python.org/3/library/logging.html#levels, but does not set the old `--log`. Because like you said, these are conceptually different. One is student facing, the other one is not. I'm fine with there being no logs in the `ansi` output, I don't think anyone was using them anyway, and the web UI is now always available.

**Comment by crossroads1112** [comment]
I don't think you can say things like "see web UI for details" because they might not have run `--output=html`. I would just suggest changing this message to say "see log for more details" since this is true irrespective of the output type (even json).


I think ansi logs should still be available somehow. If check50 were used in another web-based ide besides the cs50 one, html output would be basically useless (we had to special case cs50 ide) and as such there'd be no way to see the log at all.

**Comment by crossroads1112** [comment]
I agree the name of the command line option shouldn't be "log" but I don't see a reason why there shouldn't be a command line option for it.

**Comment by Jelleas** [comment]
My reason for nixing it is that it's unused, and only affects the ansi output mode. But it's a fair argument that the web UI might be unavailable in a web environment, and might as well handle that scenario.

As for what to call it... --details, --check-logs?
