### ISSUE TITLE
Codec failure

### ISSUE THREAD

**Issue by rbowden91** [cs50/check50#94]
Currently, if I run on the attached caesar.c:

check50 -d --offline cs50/2017/fall/caesar caesar.c

I get:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/check50.py", line 185, in excepthook
    cleanup()
  File "/usr/local/lib/python2.7/dist-packages/check50.py", line 170, in cleanup
    shutil.rmtree(config.tempdir)
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/tmpedXoxi'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/check50", line 9, in <module>
    load_entry_point('check50==2.2.2', 'console_scripts', 'check50')()
  File "/usr/local/lib/python2.7/dist-packages/check50.py", line 151, in main
    print_json(results)
  File "/usr/local/lib/python2.7/dist-packages/check50.py", line 250, in print_json
    print(json.dumps(output, cls=Encoder))
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 13: invalid start byte

```

My current fix is appending ".decode('latin-1')" to the end of this line:
https://github.com/cs50/check50/blob/c054d44d74d6074c23b2ad6747fc14e2e14c3835/check50.py#L244

The issue is that the incorrect student submissions shifts an ascii value outside of the 0-127 range. Not sure if my fix is the right thing to do, but works for the time being.

**Comment by rbowden91** [comment]
Oops, forgot to attach the file! (Changed from caesar.c to caesar.txt to appease GitHub)

[caesar.txt](https://github.com/cs50/check50/files/1986344/caesar.txt)

**Comment by crossroads1112** [comment]
Hmmm... I can't actually replicate this. This program almost intermediately fails the `cs50/2017/x/caesar` checks because it doesn't print before its output `ciphertext:`  but even after removing that from the check, I get the following json output (similarly renamed to appease GitHub)

[caesar.txt](https://github.com/cs50/check50/files/2121137/caesar.txt)

**Comment by rbowden91** [comment]
My best guess is that your /usr/bin/env python is defaulting to python3? Mine is defaulting to python2.7. So I guess this more specifically is a part of the code that isn't backwards-compatible with python's new string handling, so either fixing that or enforcing python3.

**Comment by crossroads1112** [comment]
Ah, yep now I can replicate. The next version of `check50` will require Python 3.6 (thank goodness). Simply adding `decode` won't work for `python3` since `decode` is not a method of `str` in `python3`. The correct answer here, I think, is just to have `pexpect` assume a `utf8` encoding in `python2`. If the program does not output `utf8` text, a `Utf8DecodeError` will be thrown and the check will fail just as is the case in python3. See #99
